In [ ]:
import numpy as np
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, LSTM, SimpleRNN

In [52]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [53]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [54]:
int_to_char = dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [55]:
char_to_int = dict((v, i) for i, v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

#### Data Preparation

In [56]:
seq_length = 1
x = []
y = []
for i in range(len(alphabets) - seq_length):
  seq_in = [alphabets[i]]
  seq_out = alphabets[i + 1]
  x += [[char_to_int[seq_in[0]]]]
  y += [[char_to_int[seq_out]]]
  print(seq_in, '->', seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [57]:
x, y

([[0],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [7],
  [8],
  [9],
  [10],
  [11],
  [12],
  [13],
  [14],
  [15],
  [16],
  [17],
  [18],
  [19],
  [20],
  [21],
  [22],
  [23],
  [24]],
 [[1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [7],
  [8],
  [9],
  [10],
  [11],
  [12],
  [13],
  [14],
  [15],
  [16],
  [17],
  [18],
  [19],
  [20],
  [21],
  [22],
  [23],
  [24],
  [25]])

#### Prepare the output variable

In [59]:
y_new = to_categorical(y)     #converting to catergorical form i.e one hot encoding
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

#### Prepare input variables

In [61]:
x = np.reshape(x, (25, 1, 1))
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [62]:
x_new = x / 25   #normalizing the data
x_new

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [63]:
x_new.shape, y_new.shape

((25, 1, 1), (25, 26))

#### Create the model

In [65]:
model = Sequential()

model.add(Dense(25, input_shape = (1, 1), activation= 'relu'))
#model.add(LSTM(32))
model.add(SimpleRNN(32))
model.add(Dense(26, activation= 'softmax'))

#### Compile the model

In [66]:
model.compile(loss= 'categorical_crossentropy', optimizer= 'adam', metrics= ['accuracy'])

#### Train the model

In [67]:
model.fit(x_new, y_new, epochs = 1000, batch_size=1)

Epoch 1/1000
25/25 [==============================] - 2s 2ms/step - loss: 3.2828 - accuracy: 0.0400
Epoch 2/1000
25/25 [==============================] - 0s 2ms/step - loss: 3.2543 - accuracy: 0.0400
Epoch 3/1000
25/25 [==============================] - 0s 2ms/step - loss: 3.2382 - accuracy: 0.0400
Epoch 4/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2274 - accuracy: 0.0000e+00
Epoch 5/1000
25/25 [==============================] - 0s 2ms/step - loss: 3.2137 - accuracy: 0.0000e+00
Epoch 6/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.2008 - accuracy: 0.0400
Epoch 7/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.1896 - accuracy: 0.0400
Epoch 8/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.1735 - accuracy: 0.0000e+00
Epoch 9/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.1606 - accuracy: 0.0400
Epoch 10/1000
25/25 [==============================] - 0s 3ms/step - loss: 3.1467 - accu

In [68]:
model.evaluate(x_new, y_new, batch_size= 1)

25/25 [==============================] - 0s 2ms/step - loss: 0.5447 - accuracy: 1.0000


[0.5446857810020447, 1.0]

#### Predict the character in sequence

In [69]:
new = 'K'
new_int = char_to_int[new]
new_int = np.reshape(new_int, (1, 1, 1))
new_int = new_int / 25
new_int

array([[[0.4]]])

In [70]:
pred = model.predict(new_int)
pred = np.argmax(pred)
pred = int_to_char[pred]
pred

1/1 [==============================] - 0s 175ms/step


'L'

#### For predicting next 3 charcters


In [24]:
seq_length = 3
x = []
y = []
for i in range(len(alphabets) - seq_length):
  seq_in = alphabets[i:i + seq_length]
  seq_out = alphabets[i + seq_length]
  x.append([char_to_int[char] for char in seq_in])
  y.append(char_to_int[seq_out])
  print(seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [25]:
x, y

([[0, 1, 2],
  [1, 2, 3],
  [2, 3, 4],
  [3, 4, 5],
  [4, 5, 6],
  [5, 6, 7],
  [6, 7, 8],
  [7, 8, 9],
  [8, 9, 10],
  [9, 10, 11],
  [10, 11, 12],
  [11, 12, 13],
  [12, 13, 14],
  [13, 14, 15],
  [14, 15, 16],
  [15, 16, 17],
  [16, 17, 18],
  [17, 18, 19],
  [18, 19, 20],
  [19, 20, 21],
  [20, 21, 22],
  [21, 22, 23],
  [22, 23, 24]],
 [3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25])

In [26]:
y_new = to_categorical(y)     #converting to catergorical form i.e one hot encoding
y_new

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [27]:
x = np.reshape(x, (len(x), seq_length, 1))
x.shape

(23, 3, 1)

In [28]:
x = x / 25   #normalizing the data
x

array([[[0.  ],
        [0.04],
        [0.08]],

       [[0.04],
        [0.08],
        [0.12]],

       [[0.08],
        [0.12],
        [0.16]],

       [[0.12],
        [0.16],
        [0.2 ]],

       [[0.16],
        [0.2 ],
        [0.24]],

       [[0.2 ],
        [0.24],
        [0.28]],

       [[0.24],
        [0.28],
        [0.32]],

       [[0.28],
        [0.32],
        [0.36]],

       [[0.32],
        [0.36],
        [0.4 ]],

       [[0.36],
        [0.4 ],
        [0.44]],

       [[0.4 ],
        [0.44],
        [0.48]],

       [[0.44],
        [0.48],
        [0.52]],

       [[0.48],
        [0.52],
        [0.56]],

       [[0.52],
        [0.56],
        [0.6 ]],

       [[0.56],
        [0.6 ],
        [0.64]],

       [[0.6 ],
        [0.64],
        [0.68]],

       [[0.64],
        [0.68],
        [0.72]],

       [[0.68],
        [0.72],
        [0.76]],

       [[0.72],
        [0.76],
        [0.8 ]],

       [[0.76],
        [0.8 ],
        [0.84]],



In [29]:
model = Sequential()

model.add(Dense(25, input_shape = (3, 1), activation= 'relu'))
model.add(LSTM(128))
model.add(Dense(26, activation= 'softmax'))

In [30]:
y_new = to_categorical(y)     #converting to catergorical form i.e one hot encoding
y_new.shape

(23, 26)

In [31]:
#Compile the model
model.compile(loss= 'categorical_crossentropy', optimizer= 'adam', metrics= ['accuracy'])

In [32]:
#Train the model
model.fit(x, y_new, epochs = 1000, batch_size=1)

Epoch 1/1000
23/23 [==============================] - 3s 8ms/step - loss: 3.2785 - accuracy: 0.0000e+00
Epoch 2/1000
23/23 [==============================] - 0s 9ms/step - loss: 3.2524 - accuracy: 0.0435
Epoch 3/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.2373 - accuracy: 0.0435
Epoch 4/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.2193 - accuracy: 0.0000e+00
Epoch 5/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.1960 - accuracy: 0.0000e+00
Epoch 6/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.1554 - accuracy: 0.0000e+00
Epoch 7/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.1018 - accuracy: 0.0000e+00
Epoch 8/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.0673 - accuracy: 0.0000e+00
Epoch 9/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.0094 - accuracy: 0.0870
Epoch 10/1000
23/23 [==============================] - 0s 5ms/step - loss: 2

In [33]:
model.evaluate(x, y_new, batch_size= 1)

23/23 [==============================] - 1s 4ms/step - loss: 0.0133 - accuracy: 1.0000


[0.013323009945452213, 1.0]

#### Predict on new sequence

In [50]:
new = 'IJK'
new_int = [char_to_int[char] for char in new]
new_int = np.reshape(new_int, (1, 3, 1))
new_int = new_int / 25
new_int

array([[[0.32],
        [0.36],
        [0.4 ]]])

In [51]:
pred = model.predict(new_int)
pred = np.argmax(pred)
pred = int_to_char[pred]
pred

1/1 [==============================] - 0s 23ms/step


'L'