In [1]:
#pip install transformers

In [2]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

In [3]:
# Load pre-trained model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name, num_labels=2)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
# define the text we want to classify
texts = ['This was not good product.','This was good product to purchase.']

In [23]:
# Tokenize the text
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='tf', max_length=30)

# Get the model's predictions
outputs = model(inputs)
logits = outputs.logits


In [24]:
# Apply softmax to get probabilities
probabilities = tf.nn.softmax(logits, axis=-1)
probabilities

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.56321883, 0.43678123],
       [0.6184586 , 0.38154134]], dtype=float32)>

In [25]:
# Get the predicted labels
predictions = tf.argmax(outputs.logits, axis=-1)

In [20]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.2687444 ,  0.01450862],
       [ 0.46941668, -0.01359442]], dtype=float32)>, hidden_states=None, attentions=None)

In [21]:
import numpy as np
np.array(predictions)

array([0, 0])

In [22]:
# Print out the results
labels = ['Negative','Positive']
for text, prediction in zip(texts, predictions):
    print(f'Text: {text}')
    print(f'Prediction: {labels[prediction]}')
    print()

Text: This was not good product.
Prediction: Negative

Text: This was good product to purchase.
Prediction: Negative

